### ISSUE TITLE
Mongo cursor exhausted Xill IDE 3.6.9

### ISSUE THREAD

**Issue by nielsrietkerk** [xillio/xill-platform#5]
Running the script in Xill IDE 3.6.9 gives me an error. However when I run the script in Xill IDE 3.6.4 the script runs fine.

Running the script in Xill IDE 3.6.9 produces the following error:
>An error occurred in a robot: Query failed with error code -5 and error message 'Cursor 167577336853 not found on server localhost:27017' on server localhost:27017

Screenshot of Mongod executable log:

![afbeelding](https://user-images.githubusercontent.com/36486184/39234549-de16e7aa-4873-11e8-9ad7-c9c338c4cb77.png)

Xill IDE log with the error:
[xill.log](https://github.com/xillio/inbox/files/1946137/xill.log)

The script that generates the error is available within the project-rivmnl-website repository. 
/project/reporting/analysis.xill

The database the analysis.xill script uses can be downloaded [here](https://wetransfer.com/downloads/26cc005f707532b3ed46fbd3195e414820180425085115/972f6805ca1a15647b9aa6248c7f9a1820180425085116/9cba12?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email).

**Comment by andrea-parrilli** [comment]
cannot find repo project-rivmnl-website, please link it.
Is it not https://github.com/xillio/project-rivm-poc?

**Comment by andrea-parrilli** [comment]
The problem seems to arise from the timeout on cursors on the mongo server and batch sizing on the client side: if the client cannot fetch all the batch before the timeout triggers, the next hasNext() on the iterator will not find the cursor.
A solution is to use the batchSize option in the Mongo.find calls. Given the observed speed on my machine, a setting of 1000 let the process continue much further than with the defaults (did not complete to the end due to other issues. Test with defaults: exception occurred around record 17000, with batch size setting, got to 187000 before interrupting).

Only change to the xill platform code, the documentation for the parameter, which is missing from the help files.
